---
title: "k mean"
author: "Yuxin"
date: "2019年3月13日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
## set functions
customKmeans<-function(dataset=NA,k=NA){
  if(is.na(dataset) || is.na(k)){
    stop("You must input valid parameters!!")
  }
 
## define distance fnction
  Eudist<-function(x,y){
    distance<-sqrt(sum((x-y)^2))
    return (distance)
  }

## set up matrix 
  rows.dataset<-nrow(dataset)
  continue.change=TRUE
  initPoint<-dataset[sample.int(rows.dataset,size = k),]
  formerPoint<-initPoint
  iterPoint<-matrix(0,nrow = k,ncol = ncol(dataset))
  
## find the distance of everypoint to the cluster
  error.matrix<-matrix(0,nrow=rows.dataset,ncol=k)
  while(continue.change){
  
    cluster.matrix<-matrix(0,nrow=rows.dataset,ncol=k)
    for(i in 1:rows.dataset){
      for(j in 1:k){
        error.matrix[i,j]<-Eudist(dataset[i,],formerPoint[j,])
      }
    }
## find the minimum value 
    for(i in 1:rows.dataset){
      cluster.matrix[i,which.min(error.matrix[i,])]<-1
    }

    for(i in 1:k){
      iterPoint[i,]<-apply(dataset[which(cluster.matrix[,i] == 1),],2,"mean")
    }
    all.true<-c()

    for(i in 1:k){
      if(all(formerPoint[i,] == iterPoint[i,]) == T){
        all.true[i]<-TRUE
      }
    }
    formerPoint = iterPoint
    continue.change=ifelse(all(all.true) == T,F,T)
  }
  colnames(iterPoint)<-colnames(dataset)
  out=list()
  out[["centers"]]<-iterPoint
  out[["distance"]]<-error.matrix
  out[["cluster"]]<-rep(1,rows.dataset)
  for(i in 1:rows.dataset){
    out[["cluster"]][i]<-which(cluster.matrix[i,] == 1)
  }
 
  return(out)
}


```



```{r}
library(MASS)
set.seed(123123)
Sigma <- matrix(c(1,0.5,0.5,1),2,2)
x1 = mvrnorm(n = 200, mu=c(0,0), Sigma)
Sigma <- matrix(c(2,0.5,0.5,2),2,2)
x2 = mvrnorm(n = 200, mu=c(0,5), Sigma)
Sigma <- matrix(c(3,0.5,0.5,3),2,2)
x3 = mvrnorm(n = 200, mu=c(6,4), Sigma)
xx = rbind(x1,x2,x3)
plot(xx)
dataset <- xx
k <- 3
```